lines := inlcude | declaration | assignment | statement


include := "include" name-list

name-list := name ["," name-list]



declaration := function | class

function := function-name block

function-name := name ["(" nonempty-parameter-list ")" name] funciton-name-tail

nonempty-parameter-list := varname ["," varname]

varname := name (":" type)

type := name

function-name-tail := $ |"(" parameter-list ")"

parameter-list := $ | nonempty-parameter-list


//// not implemented beyond this point


statement := if-statement | control-statement | function-call


if-statement := "if" boolean block "else" block

block := start-block lines end-block


control-statement := "return"


function-call := dot-path function-name

dot-path := [name "."]


varname ::= name name-arg-list
name-arg-list ::= e
name-arg-list ::= arg-list name name-arg-list

name ::= token name
name ::= \ CRLF name


if this is a number
  print this
else
	print that

if value, true block else false block =

1. define precedance for functions.

2. spaces allowed when declaring/using functions -- however these do not
distinguish a name, i.e. for all intents and purposes the spaces might as well
not be there.

